Repository GSG-G10/Photography, pull requests merged in 2021-08, with the labels that each got.

#8 create file structure #1
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/index.js
  public/photographer.html
  public/style.css
  server/app.js
  server/controllers/index.js
  server/database/db_build.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/index.js
Labels: Awaiting Review

#9 creat home page
  public/img/reinhart-julian-WxM465oM4j4-unsplash.jpg
  public/index.html
  public/style.css
Labels: Done

#10 home page responsiv
  public/index.html
  public/style.css
Labels: Awaiting Review

#11 create the html and css for the photographer page #5
  public/images/logo.png
  public/photographer.html
  public/photographerPage/photographer.html
  public/photographerPage/style.css
Labels: Awaiting Review

#13 make the photographer page responsive #12
  public/photographerPage/style.css
Labels: Awaiting Review

#14 Creat Server
  package.json
  public/images/reinhart-julian-WxM465oM4j4-unsplash.jpg
  public/index.html
  public/photographerPage/photographer.html
  public/style.css
  server/app.js
  server/index.js
Labels: Done

#16 create initial database #7
  server/database/db_build.sql
  server/database/db_connection.js
Labels: Done

#17 Creat Post Data & Creat Error 404 Function
  public/index.html
  public/photographerPage/photographer.html
  public/photographerPage/style.css
  public/style.css
  server/app.js
  server/controllers/errors.js
  server/controllers/index.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/database/quires/postData.js
  server/index.js
Labels: Awaiting Review

#22 Creat Error Page
  public/error/404.html
  public/error/500.html
  server/app.js
  server/controllers/errors.js
  server/controllers/index.js
  server/router/index.js
Labels: Awaiting Review, Done

#23 create the postData #19
  package.json
  public/index.html
  server/controllers/index.js
  server/database/db_connection.js
  server/database/quires/getData.js
  server/database/quires/postData.js
  server/router/index.js
Labels: Done

#24 20 fetch customers data
  package-lock.json
  package.json
  public/index.js
  public/photographerPage/photographer.html
  server/app.js
  server/database/quires/getData.js
  server/database/quires/index.js
  server/database/quires/postData.js
  server/router/index.js
Labels: Done

#27 DATABASE_URL
  server/database/db_connection.js
Labels: Awaiting Review

#28 ssl
  server/database/db_build.js
  server/database/db_connection.js
Labels: Awaiting Review

#31 Readme File
  README.md
Labels: Done

#35 add the schema to the read me #34
  README.md
  public/img/reinhart-julian-WxM465oM4j4-unsplash.jpg
Labels: Awaiting Review
